(()=>{'use strict';
const $=id=>document.getElementById(id),frame=$('appFrame'),THEME='atelier-one-theme',DB='my-company-portable-v1',STORE='state',KEY='company';let theme=localStorage.getItem(THEME)||'dark',dbp,mode='all';
function shell(){let s=document.getElementById('atelier-shell-fix');if(!s){s=document.createElement('style');s.id='atelier-shell-fix';document.head.appendChild(s)}s.textContent=`
:root{--shell-h:64px}
body{overflow:hidden!important}
#appFrame{position:fixed!important;left:0!important;right:0!important;top:var(--shell-h)!important;bottom:0!important;width:100%!important;height:calc(100dvh - var(--shell-h))!important;z-index:0!important}
.shellTopbar{position:fixed!important;z-index:20!important;top:0!important;left:0!important;right:0!important;height:var(--shell-h)!important;padding:10px 12px!important;display:flex!important;align-items:center!important;gap:8px!important;background:var(--bg)!important;border-bottom:1px solid var(--line)!important;box-shadow:none!important;pointer-events:auto!important}
.brandChip{height:44px!important;min-width:0!important;max-width:none!important;flex:1!important;padding:7px 10px!important;border-radius:14px!important;box-shadow:none!important;background:var(--bg-soft)!important}
.brandMark{width:30px!important;height:30px!important;flex:0 0 30px!important}.brandMeta{overflow:hidden!important}.brandMeta span{display:none!important}
.topActions{height:44px!important;flex:0 0 auto!important;padding:3px!important;border-radius:14px!important;box-shadow:none!important;background:var(--bg-soft)!important}.topActions button{width:36px!important;height:36px!important}
.fabCluster{display:none!important}
#cloudSheet{z-index:40!important}#sheetBackdrop{z-index:39!important}
@media(min-width:861px){:root{--shell-h:68px}.shellTopbar{padding:12px 18px!important}.brandChip{flex:0 1 420px!important}.brandMeta span{display:block!important}}
`;}
function toast(m){const e=$('toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(e._t);e._t=setTimeout(()=>e.classList.remove('show'),2200)}
function actual(){return theme==='system'?(matchMedia('(prefers-color-scheme:light)').matches?'light':'dark'):theme}
function frameTheme(){try{const d=frame.contentDocument;if(!d)return;let s=d.getElementById('atelier-theme-override');if(!s){s=d.createElement('style');s.id='atelier-theme-override';d.head.appendChild(s)}const a=actual();s.textContent=`body{font-family:Inter,"SF Pro Text",-apple-system,BlinkMacSystemFont,sans-serif!important}.panel,.project-card,.task-card,.member-card,.modal,.sheet,.dialog,.card{border-radius:18px!important;box-shadow:none!important}.primary,.secondary,.text-button,button,select,input,textarea{border-radius:12px!important}@media(max-width:720px){main{padding-top:0!important}.office,.office-panel{min-height:0!important}}`+(a==='light'?`:root{color-scheme:light!important;--blue:#0071e3!important}body{background:#f5f5f7!important;color:#1d1d1f!important}.panel,.project-card,.task-card,.member-card,.topbar,.sidebar{background:#fff!important;border-color:rgba(29,29,31,.10)!important}.primary{background:#0071e3!important;color:#fff!important}`:`:root{color-scheme:dark!important;--blue:#0a84ff!important}`)}catch{}}
function apply(v=theme){theme=v;localStorage.setItem(THEME,v);const a=actual();document.documentElement.dataset.theme=a;document.querySelector('meta[name="theme-color"]')?.setAttribute('content',a==='light'?'#f5f5f7':'#0b0f14');document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===v));frameTheme()}
async function db(){if(dbp)return dbp;dbp=new Promise((ok,no)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE)};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)});return dbp}
async function state(){const d=await db();return new Promise((ok,no)=>{const t=d.transaction(STORE,'readonly'),r=t.objectStore(STORE).get(KEY);r.onsuccess=()=>ok(r.result||{assets:[]});r.onerror=()=>no(r.error)})}
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));const bytes=n=>n<1024?n+' B':n<1048576?(n/1024).toFixed(1)+' KB':(n/1048576).toFixed(2)+' MB';
function kind(a){const n=(a.name||'').toLowerCase(),m=(a.mime||'').toLowerCase();if(/\.(html?|zip|js|css|json|md)$/.test(n)||m.includes('html')||m.includes('zip'))return'tool';if(m.startsWith('image/')||m.startsWith('audio/')||m.startsWith('video/')||/\.(png|jpg|jpeg|webp|mp3|wav|glb|gltf)$/.test(n))return'media';return'other'}
function raw(b){const x=atob(b),a=new Uint8Array(x.length);for(let i=0;i<x.length;i++)a[i]=x.charCodeAt(i);return a}
async function asset(id){return((await state()).assets||[]).find(a=>a.id===id)}
async function openAsset(id,save=false){const a=await asset(id);if(!a?.base64)return toast('ファイルを開けません');const u=URL.createObjectURL(new Blob([raw(a.base64)],{type:a.mime||'application/octet-stream'})),x=document.createElement('a');x.href=u;if(save){x.download=a.name||'download';x.click()}else window.open(u,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(u),60000)}
async function library(){const list=$('libraryList'),stats=$('libraryStats');if(!list||!stats)return;try{const s=await state(),q=($('librarySearch')?.value||'').toLowerCase();let a=[...(s.assets||[])];if(mode!=='all')a=a.filter(x=>kind(x)===mode);if(q)a=a.filter(x=>(x.name||'').toLowerCase().includes(q));stats.textContent=`全 ${s.assets?.length||0} 件 / 表示 ${a.length} 件`;list.innerHTML=a.length?a.map(x=>`<div class="assetCard"><div class="assetMeta"><strong>${esc(x.name||'untitled')}</strong><small>${esc(x.mime||'file')} · ${bytes(Number(x.size||0))}</small></div><div class="btnRow"><button class="action" data-o="${esc(x.id)}">開く</button><button class="action" data-s="${esc(x.id)}">保存</button></div></div>`).join(''):'<div class="emptyState">アップロード済みファイルはまだありません。</div>';list.querySelectorAll('[data-o]').forEach(b=>b.onclick=()=>openAsset(b.dataset.o));list.querySelectorAll('[data-s]').forEach(b=>b.onclick=()=>openAsset(b.dataset.s,true))}catch{stats.textContent='ライブラリの読み込みに失敗しました'}}
shell();frame.addEventListener('load',()=>{frameTheme();library()});$('themeQuick')?.addEventListener('click',()=>{const a=['dark','light','system'];apply(a[(a.indexOf(theme)+1)%3])});document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>apply(b.dataset.themeChoice)));$('librarySearch')?.addEventListener('input',library);$('refreshLibrary')?.addEventListener('click',library);$('filterAll')?.addEventListener('click',()=>{mode='all';library()});$('filterTools')?.addEventListener('click',()=>{mode='tool';library()});$('filterMedia')?.addEventListener('click',()=>{mode='media';library()});matchMedia('(prefers-color-scheme:light)').addEventListener('change',()=>theme==='system'&&apply('system'));apply(theme);library();
})();