(()=>{
'use strict';
const DB_NAME='my-company-portable-v1', DB_VERSION=1, STORE='state', COMPANY_KEY='company';
const THEME_KEY='atelier-one-theme';
const $=id=>document.getElementById(id);
const frame=$('appFrame'), fab=$('cloudFab'), sheet=$('cloudSheet'), backdrop=$('sheetBackdrop');
let dbPromise=null, themeMode=localStorage.getItem(THEME_KEY)||'dark', libraryMode='all';
function toast(msg){const el=$('toast');if(!el)return;el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)}
function bytes(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(2)+' MB'}
function fmt(ts){if(!ts)return'-';try{return new Date(ts).toLocaleString('ja-JP')}catch{return ts}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function readState(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(COMPANY_KEY);req.onsuccess=()=>resolve(req.result||{assets:[]});req.onerror=()=>reject(req.error)})}
function resolveTheme(){if(themeMode==='system')return matchMedia('(prefers-color-scheme: light)').matches?'light':'dark';return themeMode}
function updateThemeColor(actual){const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.content=actual==='light'?'#f5f5f7':'#0b0f14'}
function injectFrameTheme(){try{const doc=frame.contentDocument;if(!doc)return;let style=doc.getElementById('atelier-theme-override');if(!style){style=doc.createElement('style');style.id='atelier-theme-override';doc.head.appendChild(style)}const actual=resolveTheme();const common=`body{font-family:Inter,"SF Pro Text",-apple-system,BlinkMacSystemFont,sans-serif!important}.primary,.secondary,.text-button,button,select,input,textarea{border-radius:12px!important}.panel,.project-card,.task-card,.member-card,.modal,.sheet,.dialog,.card{border-radius:18px!important}.panel,.project-card,.task-card,.member-card{box-shadow:none!important}@media(max-width:720px){main{padding-top:0!important}.office{min-height:0!important;height:auto!important}.office-panel{min-height:0!important}}`;const dark=`:root{color-scheme:dark!important;--blue:#0a84ff!important}`;const light=`:root{color-scheme:light!important;--blue:#0071e3!important}body{background:#f5f5f7!important;color:#1d1d1f!important}.panel,.project-card,.task-card,.member-card,.topbar,.sidebar{background:#fff!important;border-color:rgba(29,29,31,.10)!important}.primary{background:#0071e3!important;color:#fff!important}`;style.textContent=common+(actual==='light'?light:dark)}catch{}}
function applyTheme(mode=themeMode){themeMode=mode;localStorage.setItem(THEME_KEY,mode);const actual=resolveTheme();document.documentElement.dataset.theme=actual;document.querySelectorAll('[data-theme-choice]').forEach(b=>b.classList.toggle('active',b.dataset.themeChoice===mode));updateThemeColor(actual);injectFrameTheme()}
function cycleTheme(){const a=['dark','light','system'];applyTheme(a[(a.indexOf(themeMode)+1)%a.length]);toast('テーマ: '+({dark:'ダーク',light:'ホワイト',system:'自動'}[themeMode]))}
function openSheet(){sheet?.classList.add('open');backdrop?.classList.add('open');sheet?.setAttribute('aria-hidden','false');renderLibrary()}
function classifyAsset(a){const name=(a.name||'').toLowerCase(),mime=(a.mime||'').toLowerCase();if(/\.(html?|zip|js|css|json|md)$/.test(name)||mime.includes('html')||mime.includes('zip')||mime.includes('javascript')||mime.includes('json'))return'tool';if(mime.startsWith('image/')||mime.startsWith('audio/')||mime.startsWith('video/')||/\.(png|jpg|jpeg|gif|webp|svg|mp3|wav|ogg|glb|gltf)$/.test(name))return'media';return'other'}
function b64(base64){const bin=atob(base64),arr=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)arr[i]=bin.charCodeAt(i);return arr}
function downloadBlob(blob,name){const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),2000)}
async function getAsset(id){const s=await readState();return(s.assets||[]).find(a=>a.id===id)}
async function openAsset(id){const a=await getAsset(id);if(!a?.base64)return toast('ファイルを開けません');const url=URL.createObjectURL(new Blob([b64(a.base64)],{type:a.mime||'application/octet-stream'}));window.open(url,'_blank','noopener');setTimeout(()=>URL.revokeObjectURL(url),120000)}
async function saveAsset(id){const a=await getAsset(id);if(!a?.base64)return toast('ファイルを保存できません');downloadBlob(new Blob([b64(a.base64)],{type:a.mime||'application/octet-stream'}),a.name||'download')}
async function renderLibrary(){const stats=$('libraryStats'),list=$('libraryList');if(!stats||!list)return;try{const state=await readState(),q=($('librarySearch')?.value||'').trim().toLowerCase();let items=[...(state.assets||[])].sort((a,b)=>String(b.created||'').localeCompare(String(a.created||'')));if(libraryMode!=='all')items=items.filter(a=>classifyAsset(a)===libraryMode);if(q)items=items.filter(a=>`${a.name||''} ${a.mime||''}`.toLowerCase().includes(q));stats.textContent=`全 ${state.assets?.length||0} 件 / 表示 ${items.length} 件`;if(!items.length){list.innerHTML='<div class="emptyState">まだライブラリに表示できるアップロードはありません。制作室から追加すると、ここに並びます。</div>';return}list.innerHTML=items.map(a=>`<div class="assetCard"><div class="assetMeta"><strong>${esc(a.name||'untitled')}</strong><small>${esc(a.mime||'application/octet-stream')} · ${bytes(Number(a.size||0))} · ${fmt(a.created)}</small></div><div class="btnRow"><button class="action" data-open-asset="${esc(a.id)}">開く</button><button class="action" data-save-asset="${esc(a.id)}">保存</button></div></div>`).join('');list.querySelectorAll('[data-open-asset]').forEach(b=>b.onclick=()=>openAsset(b.dataset.openAsset));list.querySelectorAll('[data-save-asset]').forEach(b=>b.onclick=()=>saveAsset(b.dataset.saveAsset))}catch{stats.textContent='ライブラリの読み込みに失敗しました'}}
$('openSheetTop')?.addEventListener('click',openSheet);$('themeQuick')?.addEventListener('click',cycleTheme);document.querySelectorAll('[data-theme-choice]').forEach(b=>b.addEventListener('click',()=>applyTheme(b.dataset.themeChoice)));$('librarySearch')?.addEventListener('input',renderLibrary);$('refreshLibrary')?.addEventListener('click',renderLibrary);$('filterAll')?.addEventListener('click',()=>{libraryMode='all';renderLibrary()});$('filterTools')?.addEventListener('click',()=>{libraryMode='tool';renderLibrary()});$('filterMedia')?.addEventListener('click',()=>{libraryMode='media';renderLibrary()});document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.pane==='library')setTimeout(renderLibrary,0)}));frame.addEventListener('load',()=>{injectFrameTheme();renderLibrary()});window.addEventListener('pageshow',injectFrameTheme);matchMedia('(prefers-color-scheme: light)').addEventListener('change',()=>{if(themeMode==='system')applyTheme('system')});applyTheme(themeMode);renderLibrary();
})();
