(()=>{
'use strict';
const DB_NAME='my-company-portable-v1', DB_VERSION=1, STORE='state', COMPANY_KEY='company';
const CFG_KEY='my-company-cloud-sync-v2';
const DEFAULT_CFG={token:'',gistId:'',gistFile:'my-company-state.json',autoSync:true,autoPull:true,deviceId:'',lastDigest:'',lastSyncedRevision:null,lastRemoteSavedAt:'',lastSyncAt:'',linkedRepos:{}};
let cfg=loadCfg(), dbPromise=null, pushTimer=null, pollTimer=null, busy=false, remoteCache=null, deferredInstall=null;
const $=id=>document.getElementById(id), frame=$('appFrame'), fab=$('cloudFab'), fabText=$('fabText'), sheet=$('cloudSheet'), backdrop=$('sheetBackdrop');
if(!cfg.deviceId){cfg.deviceId='dev-'+crypto.randomUUID().slice(0,8);saveCfg();}
function loadCfg(){try{return {...DEFAULT_CFG,...JSON.parse(localStorage.getItem(CFG_KEY)||'{}')}}catch{return {...DEFAULT_CFG}}}
function saveCfg(){localStorage.setItem(CFG_KEY,JSON.stringify(cfg));renderMeta();}
function toast(msg){const el=$('toast');el.textContent=msg;el.classList.add('show');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('show'),2600)}
function fmt(ts){if(!ts)return'-';try{return new Date(ts).toLocaleString('ja-JP')}catch{return ts}}
function bytes(n){if(n<1024)return n+' B';if(n<1048576)return(n/1024).toFixed(1)+' KB';return(n/1048576).toFixed(2)+' MB'}
function setStatus(kind,title,detail){const el=$('syncStatus');el.className='statusBox '+(kind||'');el.querySelector('strong').textContent=title;el.querySelector('small').textContent=detail||'';fab.className=kind||'';fabText.textContent=kind==='busy'?'SYNC…':kind==='conflict'?'CONFLICT':kind==='bad'?'SYNC !':'SYNC';}
function openSheet(){sheet.classList.add('open');backdrop.classList.add('open');sheet.setAttribute('aria-hidden','false');refreshStateInfo();refreshProjects();}
function closeSheet(){sheet.classList.remove('open');backdrop.classList.remove('open');sheet.setAttribute('aria-hidden','true')}
async function openDb(){if(dbPromise)return dbPromise;dbPromise=new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,DB_VERSION);req.onupgradeneeded=()=>{if(!req.result.objectStoreNames.contains(STORE))req.result.createObjectStore(STORE)};req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error)});return dbPromise}
async function readState(){const db=await openDb();return new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readonly'),req=tx.objectStore(STORE).get(COMPANY_KEY);req.onsuccess=()=>resolve(req.result||{revision:0,projects:[],tasks:[],records:[],assets:[],notes:[],audit:[]});req.onerror=()=>reject(req.error)})}
async function writeState(state){const db=await openDb();await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(state,COMPANY_KEY);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||new Error('保存を中断しました'))});}
async function digestText(text){const buf=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return [...new Uint8Array(buf)].map(v=>v.toString(16).padStart(2,'0')).join('')}
async function localSnapshot(){const state=await readState();const stateText=JSON.stringify(state);const digest=await digestText(stateText);return{state,stateText,digest,revision:Number(state.revision||0),size:new Blob([stateText]).size}}
function authHeaders(json=false){if(!cfg.token)throw new Error('GitHub Tokenを設定してください');const h={'Accept':'application/vnd.github+json','X-GitHub-Api-Version':'2022-11-28','Authorization':'Bearer '+cfg.token};if(json)h['Content-Type']='application/json';return h}
async function gh(url,opt={}){const res=await fetch(url,{...opt,headers:{...authHeaders(!!opt.body),...(opt.headers||{})}});let data=null;const text=await res.text();if(text){try{data=JSON.parse(text)}catch{data=text}}if(!res.ok){const e=new Error((data&&data.message)||('GitHub API '+res.status));e.status=res.status;e.data=data;throw e}return data}
function gistApi(){if(!cfg.gistId)throw new Error('Gist IDを設定してください');return'https://api.github.com/gists/'+encodeURIComponent(cfg.gistId)}
async function getGistPayload(){const data=await gh(gistApi());const f=data.files?.[cfg.gistFile];if(!f)return{data,payload:null};let text=f.content||'';if(f.truncated&&f.raw_url){const r=await fetch(f.raw_url,{headers:authHeaders(false)});if(!r.ok)throw new Error('Gist本文を取得できません');text=await r.text()}let payload;try{payload=JSON.parse(text)}catch{throw new Error('同期GistのJSON形式が不正です')}if(payload.format!=='my-company-cloud'||payload.version!==2||!payload.state)throw new Error('MY COMPANY同期データではありません');return{data,payload}}
async function pushCloud(force=false){if(busy)return;busy=true;setStatus('busy','クラウドへ保存中','この端末の最新状態をGistへ反映しています。');try{const snap=await localSnapshot();if(snap.size>9*1024*1024&&!force)throw new Error('同期データが9MBを超えています。大きな素材は外部Repoへ置き、会社データを軽くしてください。');const now=new Date().toISOString();const payload={format:'my-company-cloud',version:2,savedAt:now,deviceId:cfg.deviceId,revision:snap.revision,sha256:snap.digest,state:snap.state};await gh(gistApi(),{method:'PATCH',body:JSON.stringify({files:{[cfg.gistFile]:{content:JSON.stringify(payload)}}})});cfg.lastDigest=snap.digest;cfg.lastSyncedRevision=snap.revision;cfg.lastRemoteSavedAt=now;cfg.lastSyncAt=now;saveCfg();remoteCache=payload;$('conflictBar').classList.remove('show');setStatus('ok','同期済み','この端末とGistは一致しています。');toast('Gistへ同期しました');}catch(e){setStatus('bad','同期失敗',e.message);toast(e.message);throw e}finally{busy=false;refreshStateInfo()}}
async function applyRemote(payload){await writeState(payload.state);cfg.lastDigest=payload.sha256||await digestText(JSON.stringify(payload.state));cfg.lastSyncedRevision=Number(payload.state.revision||payload.revision||0);cfg.lastRemoteSavedAt=payload.savedAt||new Date().toISOString();cfg.lastSyncAt=new Date().toISOString();saveCfg();remoteCache=payload;$('conflictBar').classList.remove('show');setStatus('ok','クラウド版を反映','MY COMPANYを再読み込みします。');toast('クラウド版を反映しました');setTimeout(()=>{frame.src='./app.html?sync='+Date.now()},250)}
async function pullCloud(force=false,background=false){if(busy)return;try{if(!background){busy=true;setStatus('busy','クラウドを確認中','他端末の更新を確認しています。')}const {payload}=await getGistPayload();if(!payload){if(!background)setStatus('ok','Gistは空です','この端末のデータをアップロードできます。');return'empty'}remoteCache=payload;const snap=await localSnapshot();const remoteDigest=payload.sha256||await digestText(JSON.stringify(payload.state));if(remoteDigest===snap.digest){cfg.lastDigest=snap.digest;cfg.lastSyncedRevision=snap.revision;cfg.lastRemoteSavedAt=payload.savedAt||cfg.lastRemoteSavedAt;cfg.lastSyncAt=new Date().toISOString();saveCfg();setStatus('ok','同期済み','この端末とGistは一致しています。');return'same'}
const hasBaseline=!!cfg.lastDigest;const localDirty=hasBaseline?snap.digest!==cfg.lastDigest:!isEmptyState(snap.state);const remoteDirty=hasBaseline?remoteDigest!==cfg.lastDigest:true;
if(force==='cloud'){await applyRemote(payload);return'pulled'}
if(force==='local'){busy=false;await pushCloud(true);return'pushed'}
if(localDirty&&remoteDirty){$('conflictBar').classList.add('show');setStatus('conflict','同期競合','この端末とクラウドの両方に未同期の変更があります。');return'conflict'}
if(remoteDirty&&!localDirty){await applyRemote(payload);return'pulled'}
if(localDirty&&!remoteDirty){busy=false;await pushCloud();return'pushed'}
return'same';}catch(e){if(!background){setStatus('bad','クラウド確認失敗',e.message);toast(e.message)}return'error'}finally{if(!background)busy=false;refreshStateInfo()}}
function isEmptyState(s){return!(s.projects?.length||s.tasks?.length||s.records?.length||s.assets?.length||s.notes?.length||s.audit?.length)}
async function syncNow(){if(!cfg.gistId||!cfg.token){openSheet();setStatus('bad','同期設定が必要','Token と Gist ID を設定してください。');return}const result=await pullCloud(false,false);if(result==='empty')await pushCloud();}
function queueAutoPush(){if(!cfg.autoSync||!cfg.gistId||!cfg.token)return;clearTimeout(pushTimer);pushTimer=setTimeout(async()=>{try{const snap=await localSnapshot();if(snap.digest!==cfg.lastDigest)await pushCloud()}catch{}},2200)}
function startPoll(){clearInterval(pollTimer);if(cfg.autoPull&&cfg.token&&cfg.gistId)pollTimer=setInterval(()=>pullCloud(false,true),30000)}
async function createGist(){try{readUiCfg();if(!cfg.token)throw new Error('先にGitHub Tokenを入力してください');setStatus('busy','Gistを作成中','同期用Gistを準備しています。');const snap=await localSnapshot(),now=new Date().toISOString(),payload={format:'my-company-cloud',version:2,savedAt:now,deviceId:cfg.deviceId,revision:snap.revision,sha256:snap.digest,state:snap.state};const data=await gh('https://api.github.com/gists',{method:'POST',body:JSON.stringify({description:'MY COMPANY cloud sync',public:false,files:{[cfg.gistFile]:{content:JSON.stringify(payload)}}})});cfg.gistId=data.id;cfg.lastDigest=snap.digest;cfg.lastSyncedRevision=snap.revision;cfg.lastRemoteSavedAt=now;cfg.lastSyncAt=now;saveCfg();writeUiCfg();setStatus('ok','Gistを作成しました','自動同期を開始しました。');toast('同期Gistを作成しました');startPoll();}catch(e){setStatus('bad','Gist作成失敗',e.message);toast(e.message)}}
function readUiCfg(){cfg.token=$('ghToken').value.trim();cfg.gistId=$('gistId').value.trim();cfg.gistFile=$('gistFile').value.trim()||'my-company-state.json';cfg.autoSync=$('autoSync').checked;cfg.autoPull=$('autoPull').checked;saveCfg()}
function writeUiCfg(){$('ghToken').value=cfg.token||'';$('gistId').value=cfg.gistId||'';$('gistFile').value=cfg.gistFile||'my-company-state.json';$('autoSync').checked=cfg.autoSync!==false;$('autoPull').checked=cfg.autoPull!==false;}
async function saveConnect(){readUiCfg();if(!cfg.token){setStatus('bad','Tokenが必要','GitHub Tokenを入力してください。');return}if(!cfg.gistId){setStatus('bad','Gist IDが必要','既存Gist IDを入力するか、新規作成してください。');return}toast('同期設定を保存しました');startPoll();await syncNow()}
async function refreshStateInfo(){try{const snap=await localSnapshot();$('localRevision').textContent=String(snap.revision);$('stateSize').textContent=bytes(snap.size);$('deviceIdText').textContent=cfg.deviceId;$('lastSync').textContent=fmt(cfg.lastSyncAt);$('cloudSaved').textContent=fmt(cfg.lastRemoteSavedAt);if(cfg.token&&cfg.gistId&&snap.digest===cfg.lastDigest)setStatus('ok','同期済み','この端末とGistは一致しています。');else if(cfg.token&&cfg.gistId&&!busy)setStatus('','同期待ち','未同期の変更がある可能性があります。');}catch(e){$('stateSize').textContent='取得失敗'}}
async function refreshProjects(){try{const state=await readState(),sel=$('projectSelect'),current=sel.value;sel.innerHTML='<option value="">プロジェクトを選択</option>'+state.projects.map(p=>`<option value="${esc(p.id)}">${esc(p.name||p.title||p.id)}</option>`).join('');if([...sel.options].some(o=>o.value===current))sel.value=current;updateProjectRepoUi();}catch{}}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function updateProjectRepoUi(){const pid=$('projectSelect').value;if(!pid){$('publishInfo').textContent='プロジェクトを選ぶと、登録済みのソース数を表示します。';return}const link=cfg.linkedRepos?.[pid];if(link){$('repoOwner').value=link.owner||'iwamotoco-source';$('repoName').value=link.repo||'';$('repoBranch').value=link.branch||'main'}const state=await readState(),sources=state.records?.filter(r=>r.kind==='source'&&r.project===pid&&typeof r.path==='string'&&typeof r.content==='string')||[];$('publishInfo').textContent=`制作室の source: ${sources.length} ファイル`}
function repoCfg(){const owner=$('repoOwner').value.trim(),repo=$('repoName').value.trim(),branch=$('repoBranch').value.trim()||'main';if(!owner||!repo)throw new Error('Owner と Repository を入力してください');return{owner,repo,branch}}
function saveRepoLink(){const pid=$('projectSelect').value;if(!pid){toast('プロジェクトを選択してください');return}const r=repoCfg();cfg.linkedRepos={...(cfg.linkedRepos||{}),[pid]:r};saveCfg();toast('リンク先を保存しました')}
async function loadRepos(){try{readUiCfg();if(!cfg.token)throw new Error('GitHub Tokenを設定してください');const data=await gh('https://api.github.com/user/repos?per_page=100&sort=updated&affiliation=owner');$('repoList').innerHTML=data.map(r=>`<option value="${esc(r.name)}"></option>`).join('');toast(`${data.length}件のRepoを取得しました`)}catch(e){toast(e.message)}}
async function publishSources(){try{readUiCfg();if(!cfg.token)throw new Error('GitHub Tokenを設定してください');const pid=$('projectSelect').value;if(!pid)throw new Error('プロジェクトを選択してください');const {owner,repo,branch}=repoCfg(),state=await readState();const sources=state.records?.filter(r=>r.kind==='source'&&r.project===pid&&safePath(r.path)&&typeof r.content==='string')||[];if(!sources.length)throw new Error('このプロジェクトに制作ソースがありません');$('publishSources').disabled=true;$('publishInfo').textContent='GitHubへ反映中…';const base='https://api.github.com/repos/'+encodeURIComponent(owner)+'/'+encodeURIComponent(repo);const ref=await gh(base+'/git/ref/heads/'+encodeURIComponent(branch));const parent=ref.object.sha;const commit=await gh(base+'/git/commits/'+parent);const blobs=[];for(let i=0;i<sources.length;i++){const s=sources[i];$('publishInfo').textContent=`Blob作成 ${i+1}/${sources.length}: ${s.path}`;const b=await gh(base+'/git/blobs',{method:'POST',body:JSON.stringify({content:s.content,encoding:'utf-8'})});blobs.push({path:s.path,mode:'100644',type:'blob',sha:b.sha})}const tree=await gh(base+'/git/trees',{method:'POST',body:JSON.stringify({base_tree:commit.tree.sha,tree:blobs})});const message=$('commitMessage').value.trim()||'Update from MY COMPANY';const next=await gh(base+'/git/commits',{method:'POST',body:JSON.stringify({message,tree:tree.sha,parents:[parent]})});await gh(base+'/git/refs/heads/'+encodeURIComponent(branch),{method:'PATCH',body:JSON.stringify({sha:next.sha,force:false})});saveRepoLink();$('publishInfo').textContent=`反映完了: ${sources.length}ファイル / ${next.sha.slice(0,7)}`;toast('GitHubへ直接反映しました');}catch(e){$('publishInfo').textContent='反映失敗: '+e.message;toast(e.message)}finally{$('publishSources').disabled=false}}
function safePath(p){return typeof p==='string'&&p.length>0&&p.length<240&&!p.startsWith('/')&&!p.split('/').some(x=>!x||x==='.'||x==='..'||x==='.git')}
async function ensurePages(){try{readUiCfg();const{owner,repo,branch}=repoCfg(),base='https://api.github.com/repos/'+encodeURIComponent(owner)+'/'+encodeURIComponent(repo)+'/pages';try{const d=await gh(base);toast('GitHub Pagesは有効です: '+(d.html_url||''));return}catch(e){if(e.status!==404)throw e}await gh(base,{method:'POST',body:JSON.stringify({source:{branch,path:'/'}})});toast('GitHub Pagesを有効化しました')}catch(e){toast('Pages設定: '+e.message)}}
function openExternal(url){window.open(url,'_blank','noopener')}
function openRepo(){try{const{owner,repo}=repoCfg();openExternal(`https://github.com/${encodeURIComponent(owner)}/${encodeURIComponent(repo)}`)}catch(e){toast(e.message)}}
function openPages(){try{const{owner,repo}=repoCfg();openExternal(`https://${owner}.github.io/${encodeURIComponent(repo)}/`)}catch(e){toast(e.message)}}
async function exportJson(){const state=await readState(),payload={format:'my-company-backup',version:1,savedAt:new Date().toISOString(),state};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='MY-COMPANY-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importJson(file){try{const data=JSON.parse(await file.text()),state=data.state||data;if(!Array.isArray(state.projects)||!Array.isArray(state.records))throw new Error('MY COMPANYバックアップ形式ではありません');await writeState(state);cfg.lastDigest='';cfg.lastSyncedRevision=null;saveCfg();toast('JSONを復元しました');setTimeout(()=>frame.src='./app.html?restore='+Date.now(),200)}catch(e){toast(e.message)}}
function attachFrame(){try{const w=frame.contentWindow,d=frame.contentDocument;w.addEventListener('company-change',queueAutoPush);d?.addEventListener('click',e=>{const a=e.target.closest?.('a');if(!a)return;try{const u=new URL(a.href,location.href);if(u.origin===location.origin&&/\/mycompany\/index\.html$/.test(u.pathname)){e.preventDefault();a.href='./app.html'}}catch{}},true);refreshProjects();refreshStateInfo();if(cfg.autoPull&&cfg.gistId&&cfg.token)setTimeout(()=>pullCloud(false,true),1000)}catch{}}
function renderMeta(){if($('deviceIdText'))$('deviceIdText').textContent=cfg.deviceId;if($('lastSync'))$('lastSync').textContent=fmt(cfg.lastSyncAt);if($('cloudSaved'))$('cloudSaved').textContent=fmt(cfg.lastRemoteSavedAt)}
function pwaCheck(){const ok='serviceWorker'in navigator&&location.protocol==='https:';const el=$('pwaStatus');el.className='statusBox '+(ok?'ok':'bad');el.querySelector('strong').textContent=ok?'PWA / オフライン対応':'PWAを利用できません';el.querySelector('small').textContent=ok?'Service Workerが利用可能です。ホーム画面追加後も起動できます。':'HTTPSで開いてください。'}

fab.addEventListener('click',openSheet);$('closeSheet').addEventListener('click',closeSheet);backdrop.addEventListener('click',closeSheet);
document.querySelectorAll('.tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.tab,.pane').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector(`.pane[data-pane="${b.dataset.pane}"]`).classList.add('active')}));
$('saveConnect').addEventListener('click',saveConnect);$('createGist').addEventListener('click',createGist);$('syncNow').addEventListener('click',()=>{readUiCfg();syncNow()});$('pushNow').addEventListener('click',()=>{readUiCfg();pushCloud(true)});$('pullNow').addEventListener('click',()=>{readUiCfg();pullCloud('cloud',false)});$('useCloud').addEventListener('click',()=>remoteCache?applyRemote(remoteCache):pullCloud('cloud',false));$('useLocal').addEventListener('click',()=>pushCloud(true));
$('openGist').addEventListener('click',()=>cfg.gistId?openExternal('https://gist.github.com/'+cfg.gistId):toast('Gist IDが未設定です'));
$('projectSelect').addEventListener('change',updateProjectRepoUi);$('loadRepos').addEventListener('click',loadRepos);$('saveRepoLink').addEventListener('click',()=>{try{saveRepoLink()}catch(e){toast(e.message)}});$('publishSources').addEventListener('click',publishSources);$('openRepo').addEventListener('click',openRepo);$('openPages').addEventListener('click',openPages);$('ensurePages').addEventListener('click',ensurePages);
$('exportJson').addEventListener('click',exportJson);$('importJsonBtn').addEventListener('click',()=>$('importJson').click());$('importJson').addEventListener('change',e=>e.target.files[0]&&importJson(e.target.files[0]));$('forgetToken').addEventListener('click',()=>{cfg.token='';saveCfg();writeUiCfg();setStatus('','Tokenを消去しました','必要なときに再入力してください。');toast('この端末のTokenを消去しました')});$('refreshApp').addEventListener('click',()=>{frame.src='./app.html?reload='+Date.now();navigator.serviceWorker?.getRegistration?.().then(r=>r?.update())});$('installPwa').addEventListener('click',async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}else toast('iPhone: Safariの共有 →「ホーム画面に追加」')});
frame.addEventListener('load',attachFrame);window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e});window.addEventListener('focus',()=>{if(cfg.autoPull&&cfg.gistId&&cfg.token)pullCloud(false,true)});document.addEventListener('visibilitychange',()=>{if(!document.hidden&&cfg.autoPull&&cfg.gistId&&cfg.token)pullCloud(false,true)});
if('serviceWorker'in navigator&&location.protocol==='https:')navigator.serviceWorker.register('./sw.js').then(()=>pwaCheck()).catch(()=>pwaCheck());else pwaCheck();
writeUiCfg();renderMeta();refreshStateInfo();startPoll();
})();
